name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    # Проверяем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # Устанавливаем Doxygen
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    # Генерация документации
    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Create gh-pages branch (if not exists)
      run: |
        if ! git ls-remote --exit-code origin gh-pages; then
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi
    # Размещение документации в ветке gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
